### ISSUE TITLE
FOV can be set in config.cfg

### ISSUE THREAD

**Issue by reddit-is-fun** [marvinl97/BO-SP-Z-FoV-Changer#1]
Are you aware that FOV can be set in the config files? Path is `~\Call of Duty - Black Ops\players\config.cfg`. You have to bind changing FOV to a key, for example to F12: `bind F12 "cg_fov 100"`. In my opinion a native way is preferred over external program.  
I'm don't know if this method works in all IW 3.0 engine Call of Duty games, but I've successfully used it also in MW1. I'm currently playing through all CoD games on PC and I will contact you if I'm unable to change FOV in one of them.

**Comment by marvinl97** [comment]
Hey!
I'm pretty sure that I already tested this. It only works when you play offline/alone. So if you want to change your FoV in online lobbies, you have to use external tools. In MW1 you could change so many things and had a nice console. If I'm not wrong, BO1 MP was the last CoD with a real console?
But nevertheless thank you for your post! =)

**Comment by reddit-is-fun** [comment]
> I'm pretty sure that I already tested this. It only works when you play offline/alone.

I wasn't aware of this, thank you. Great that the FOV can be customized in online Zombie matches.

> If I'm not wrong, BO1 MP was the last CoD with a real console?

That's not something I'm not exactly aware of, but I know that the console was eventually dropped. I think the console was absent in MW2.
If I'm not wrong, BO1 MP was the last CoD with a real console?
